version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      APP_SECRET: change-me
      DB_URL: sqlite:///./app.db
      CORS_ORIGINS: http://localhost:5173
    volumes:
      - ../backend:/app/backend
      - ../frontend/dist:/app/frontend/dist
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload
